# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "kuleuven-engineering-science-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Benjamin Eeckhout <https://github.com/benjamineeckh>"]
license = "MIT"
description = "thesis template for engineering science at KU Leuven"
# homepage = ""
repository = "https://github.com/benjamineeckh/kul-typst-template"
keywords = ["thesis", "KU Leuven", "Katholieke Universiteit Leuven", "masterthesis"]
categories = ["thesis"]
# disciplines = []
compiler = ""
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
	"references"
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
